-- MySQL Script generated by MySQL Workbench
-- Sun Aug 27 19:51:24 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db` DEFAULT CHARACTER SET utf8mb4 ;
USE `db` ;

-- -----------------------------------------------------
-- Table `db`.`admin_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`admin_user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `admin_role_id` INT NOT NULL COMMENT '管理ユーザの役割',
  `admin_group_id` INT NOT NULL COMMENT '管理グループ',
  `enable_flag` TINYINT NOT NULL COMMENT '有効か？',
  `name` VARCHAR(20) NOT NULL COMMENT 'フルネーム',
  `username` VARCHAR(20) NOT NULL COMMENT 'ユーザ名',
  `password` CHAR(64) NOT NULL COMMENT 'パスワード(SHA-256)',
  `email` VARCHAR(100) NOT NULL COMMENT 'メールアドレス',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `updated` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
COMMENT = '管理ユーザ';


-- -----------------------------------------------------
-- Table `db`.`admin_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`admin_role` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(20) NOT NULL COMMENT '名前',
  `roles` TEXT NOT NULL COMMENT '役割の一覧',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `updated` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '管理ユーザの役割';


-- -----------------------------------------------------
-- Table `db`.`m_admin_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`m_admin_role` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `cd` VARCHAR(20) NOT NULL COMMENT '識別子',
  `name` VARCHAR(20) NOT NULL COMMENT '名前',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cd_UNIQUE` (`cd` ASC))
ENGINE = InnoDB
COMMENT = '管理画面の役割';


-- -----------------------------------------------------
-- Table `db`.`log_admin_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`log_admin_login` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `admin_user_id` INT NOT NULL COMMENT '管理ユーザ',
  `ip_address` VARCHAR(40) NOT NULL COMMENT 'IPアドレス',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  PRIMARY KEY (`id`),
  INDEX `created` (`created` ASC))
ENGINE = InnoDB
COMMENT = '管理画面のログイン履歴';


-- -----------------------------------------------------
-- Table `db`.`log_admin_login_error`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`log_admin_login_error` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `ip_address` VARCHAR(40) NOT NULL COMMENT 'IPアドレス',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  PRIMARY KEY (`id`),
  INDEX `created` (`created` ASC))
ENGINE = InnoDB
COMMENT = '管理画面のログイン失敗の履歴';


-- -----------------------------------------------------
-- Table `db`.`admin_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`admin_group` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(20) NOT NULL COMMENT '名前',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '管理グループ';


-- -----------------------------------------------------
-- Table `db`.`property`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`property` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `cd` VARCHAR(20) NOT NULL COMMENT '識別子',
  `property_type_id` INT NOT NULL COMMENT 'プロパティの型',
  `property_group_id` INT NOT NULL COMMENT 'プロパティのグループ',
  `name` VARCHAR(20) NOT NULL COMMENT '名前',
  `description` TEXT NOT NULL COMMENT '説明文',
  `default_value` TEXT NOT NULL COMMENT 'デフォルト値',
  `order` INT NOT NULL COMMENT '順序',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `updated` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cd` (`cd` ASC),
  INDEX `order` (`order` ASC))
ENGINE = InnoDB
COMMENT = 'プロパティ';


-- -----------------------------------------------------
-- Table `db`.`m_property_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`m_property_type` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `cd` VARCHAR(20) NOT NULL COMMENT '識別子',
  `name` VARCHAR(20) NOT NULL COMMENT '名前',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cd` (`cd` ASC))
ENGINE = InnoDB
COMMENT = 'プロパティの型';


-- -----------------------------------------------------
-- Table `db`.`property_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`property_value` (
  `property_cd` VARCHAR(20) NOT NULL COMMENT 'プロパティの識別子',
  `value` TEXT NOT NULL COMMENT '値',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  PRIMARY KEY (`property_cd`))
ENGINE = InnoDB
COMMENT = 'プロパティの値';


-- -----------------------------------------------------
-- Table `db`.`property_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`property_group` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(20) NOT NULL COMMENT '名前',
  `description` TEXT NOT NULL COMMENT '説明文',
  `order` INT NOT NULL COMMENT '順序',
  PRIMARY KEY (`id`),
  INDEX `order` (`order` ASC))
ENGINE = InnoDB
COMMENT = 'プロパティのグループ';


-- -----------------------------------------------------
-- Table `db`.`log_error`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`log_error` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `severity` VARCHAR(20) NOT NULL COMMENT '深刻度',
  `url` VARCHAR(100) NOT NULL COMMENT 'URL',
  `message` TEXT NOT NULL COMMENT 'エラーメッセージ',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  PRIMARY KEY (`id`),
  INDEX `created` (`created` ASC))
ENGINE = InnoDB
COMMENT = 'エラー履歴';


-- -----------------------------------------------------
-- Table `db`.`log_mail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`log_mail` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `to` TEXT NOT NULL COMMENT '送信先',
  `from` TEXT NOT NULL COMMENT '送信元',
  `subject` TEXT NOT NULL COMMENT '題名',
  `message` TEXT NOT NULL COMMENT '本文',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'メール送信履歴';


-- -----------------------------------------------------
-- Table `db`.`sysmail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`sysmail` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `sysmail_type_id` INT NOT NULL COMMENT 'メールテンプレートの種類',
  `enable_flag` TINYINT NOT NULL COMMENT '有効か？',
  `period_flag` TINYINT NOT NULL COMMENT '有効期間を使うか？',
  `period_begin` DATETIME NOT NULL COMMENT '有効期間の開始日時',
  `period_end` DATETIME NOT NULL COMMENT '有効期間の終了日時',
  `name` VARCHAR(20) NOT NULL COMMENT '管理用の名前',
  `note` TEXT NOT NULL COMMENT 'メモ欄',
  `to` TEXT NOT NULL COMMENT '送信先メールアドレス',
  `from` VARCHAR(100) NOT NULL COMMENT '送信元メールアドレス',
  `subject` VARCHAR(100) NOT NULL COMMENT '題名',
  `message` TEXT NOT NULL COMMENT '本文',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `updated` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'メールテンプレート';


-- -----------------------------------------------------
-- Table `db`.`m_sysmail_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`m_sysmail_type` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `cd` VARCHAR(20) NOT NULL COMMENT '識別子',
  `name` VARCHAR(20) NOT NULL COMMENT '名前',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cd` (`cd` ASC))
ENGINE = InnoDB
COMMENT = 'メールテンプレートの種類';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db`.`admin_user`
-- -----------------------------------------------------
START TRANSACTION;
USE `db`;
INSERT INTO `db`.`admin_user` (`id`, `admin_role_id`, `admin_group_id`, `enable_flag`, `name`, `username`, `password`, `email`, `created`, `updated`) VALUES (1, 1, 1, 1, 'Administrator', 'admin', 'a7d026b5de30d5e0773a38324f84a73e5e8fa815641089ae835deaa02eed2f62', 'info@entap.co.jp', '0000-00-00 00:00:00', '0000-00-00 00:00:00');

COMMIT;


-- -----------------------------------------------------
-- Data for table `db`.`admin_role`
-- -----------------------------------------------------
START TRANSACTION;
USE `db`;
INSERT INTO `db`.`admin_role` (`id`, `name`, `roles`, `created`, `updated`) VALUES (1, '特権', '*', '0000-00-00 00:00:00', '0000-00-00 00:00:00');

COMMIT;


-- -----------------------------------------------------
-- Data for table `db`.`m_admin_role`
-- -----------------------------------------------------
START TRANSACTION;
USE `db`;
INSERT INTO `db`.`m_admin_role` (`id`, `cd`, `name`) VALUES (DEFAULT, '*', '全ての操作');
INSERT INTO `db`.`m_admin_role` (`id`, `cd`, `name`) VALUES (DEFAULT, 'admin_user', 'すべての管理ユーザを管理');
INSERT INTO `db`.`m_admin_role` (`id`, `cd`, `name`) VALUES (DEFAULT, 'admin_user_local', '同じグループの管理ユーザを管理');
INSERT INTO `db`.`m_admin_role` (`id`, `cd`, `name`) VALUES (DEFAULT, 'admin_group', '管理グループを管理');
INSERT INTO `db`.`m_admin_role` (`id`, `cd`, `name`) VALUES (DEFAULT, 'admin_role', '管理ユーザの役割を管理');
INSERT INTO `db`.`m_admin_role` (`id`, `cd`, `name`) VALUES (DEFAULT, 'log', 'ログ');
INSERT INTO `db`.`m_admin_role` (`id`, `cd`, `name`) VALUES (DEFAULT, 'property', 'システム設定');
INSERT INTO `db`.`m_admin_role` (`id`, `cd`, `name`) VALUES (DEFAULT, 'sysmail', 'メールテンプレート');

COMMIT;


-- -----------------------------------------------------
-- Data for table `db`.`admin_group`
-- -----------------------------------------------------
START TRANSACTION;
USE `db`;
INSERT INTO `db`.`admin_group` (`id`, `name`) VALUES (1, '標準グループ');

COMMIT;


-- -----------------------------------------------------
-- Data for table `db`.`m_property_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `db`;
INSERT INTO `db`.`m_property_type` (`id`, `cd`, `name`) VALUES (1, 'integer', '整数');
INSERT INTO `db`.`m_property_type` (`id`, `cd`, `name`) VALUES (2, 'decimal', '少数');
INSERT INTO `db`.`m_property_type` (`id`, `cd`, `name`) VALUES (3, 'string', '文字列');
INSERT INTO `db`.`m_property_type` (`id`, `cd`, `name`) VALUES (4, 'text', '複数行文字列');
INSERT INTO `db`.`m_property_type` (`id`, `cd`, `name`) VALUES (5, 'boolean', '真偽値');

COMMIT;

